config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
get "up" => "rails/health#show", as: :rails_health_check

root "pages#index"

resources :congregacoes
resources :entradas
resources :literaturas 
get "literaturas_relatorio", to: "literaturas#relatorio"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/congregacao.rb
class Congregacao < ApplicationRecord
  validates :descricao, presence: true
  has_many :literaturas
  has_many :entradas
end

app/models/entrada.rb
class Entrada < ApplicationRecord
  belongs_to :congregacao
end

app/models/literatura.rb
class Literatura < ApplicationRecord
  belongs_to :congregacao

  def self.relatorio
    sql = <<-SQL
    SELECT
        congregacoes.descricao AS congregacao,
        literaturas.trimestre AS trimestre_literatura,
        literaturas.ano,
        literaturas.valor AS valor_a_pagar,
        COALESCE(SUM(entradas.valor), 0) AS valor_pago,
        (literaturas.valor - COALESCE(SUM(entradas.valor), 0)) AS valor_pendente
    FROM literaturas
    INNER JOIN congregacoes ON literaturas.congregacao_id = congregacoes.id
    LEFT JOIN entradas 
        ON entradas.congregacao_id = congregacoes.id
        AND entradas.trimestre = literaturas.trimestre
        AND entradas.ano = literaturas.ano
        WHERE literaturas.trimestre = 3
    GROUP BY
        congregacoes.descricao,
        literaturas.trimestre,
        literaturas.ano,
        literaturas.valor
    ORDER BY 
        congregacoes.descricao    

    SQL
  
    ActiveRecord::Base.connection.execute(sql)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/congregacoes_controller.rb
class CongregacoesController < ApplicationController

  before_action :set_congregacao, only: [:show, :edit, :destroy, :update]
  def index
    @congregacoes = Congregacao.order(:descricao)
  end

  def show
    
  end

  def new
    @congregacao = Congregacao.new
  end

  def create
    @congregacao = Congregacao.new(congregacao_params)
    if @congregacao.save
      redirect_to  congregacoes_path  , notice: 'Congregação criada com sucesso.'
    else
      render :new
    end
  end
  
  def edit 
    
  end

  def update
    if @congregacao.update(congregacao_params)
      redirect_to @congregacao, notice: 'Congregação editada com sucesso'      
    else
      render :edit
    end
  end

  def destroy
    @congregacao.destroy!
    redirect_to congregacoes_path, notice: 'Congregação excluída com sucesso'
  end

  private
  def set_congregacao
    @congregacao = Congregacao.find(params[:id])
  end
  def congregacao_params
    params.require(:congregacao).permit(:descricao)
  end
end

app/controllers/entradas_controller.rb
class EntradasController < ApplicationController
  before_action :set_entrada, only: [:show, :edit, :update, :destroy] 

  def index
    @entradas = Entrada.joins(:congregacao).order('congregacoes.descricao', :congregacao_id, :trimestre)
  end
  
  

def edit
  @congregacoes = Congregacao.all

end

def show

end

def new
  @entrada = Entrada.new
  @congregacoes = Congregacao.all
end


def create
  @entrada = Entrada.new(entrada_params)
  if @entrada.save
    redirect_to entradas_path, notice: 'Entrada criada com sucesso'
  else
    render :new
  end
end
def update
if @entrada.update(entrada_params)
   redirect_to entradas_path, notice: 'Entrada editada com sucesso'
else
  render :edit
end

end

def destroy
  @entrada.destroy 

  redirect_to entradas_path , notice: 'Entrada deletada com sucesso'
end

private

def set_entrada
  @entrada = Entrada.find(params[:id])
end


def entrada_params
  params.require(:entrada).permit( :congregacao_id, :valor, :trimestre, :ano)
end


end

app/controllers/literaturas_controller.rb
class LiteraturasController < ApplicationController
  before_action :set_literatura, only: [:show, :edit, :update, :destroy]

  def index
    @literaturas = Literatura.order(:id)
  end

  def new
    @literatura = Literatura.new
    @congregacoes = Congregacao.all
  end

  def show
    
  end

  def edit
    @congregacoes = Congregacao.all
  end

  def create
    @literatura = Literatura.new(literatura_params)
    if @literatura.save
      redirect_to literaturas_path, notice: 'Literatura criada com sucesso'
    else
      render :new
    end
  end

  def update
    if @literatura.update(literatura_params)
      redirect_to literaturas_path, notice: 'Literatura editada com sucesso'
    else
      render :edit
    end
  end

  def destroy
    @literatura.destroy
    redirect_to literaturas_path, notice: 'Literatura excluída com sucesso'
  end

  def relatorio
    raw_result = Literatura.relatorio
    @relatorio = raw_result.map do |row|
      total = row['valor_a_pagar'].to_f
      pago = row['valor_pago'].to_f
      percentual_pago = total > 0 ? (pago / total * 100) : 0
  
      linha_classe = if percentual_pago >= 100
                       'table-success'
                     elsif percentual_pago >= 80
                       'table-warning'
                     else
                       'table-danger'
                     end
  
      row.merge('percentual_pago' => percentual_pago, 'linha_classe' => linha_classe)
    end
  
    Rails.logger.debug "Tipo de @relatorio: #{@relatorio.class.name}" # Verifique o tipo
    Rails.logger.debug "Conteúdo de @relatorio: #{@relatorio.inspect}" # Verifique o conteúdo
  end
  
  
  private

  def set_literatura
    @literatura = Literatura.find(params[:id])
  end

  def literatura_params
    params.require(:literatura).permit(:congregacao_id, :trimestre, :ano, :valor)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/congregacoes_helper.rb
module CongregacoesHelper
end

app/helpers/entrada_helper.rb
module EntradaHelper
end

app/helpers/literatura_helper.rb
module LiteraturaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/congregacoes/edit.html.erb
<div id="main">
  <header class="mb-3">
    <a href="#" class="burger-btn d-block d-xl-none">
      <i class="bi bi-justify fs-3"></i>
    </a>
  </header>
  <div class="page-heading">
    <div class="page-title">
      <div class="row">
        <div class="col-12 col-md-6 order-md-1 order-last">
          <h3>Congregação</h3>
          <p class="text-subtitle text-muted"></p>
        </div>
        <div class="col-12 col-md-6 order-md-2 order-first">
        </div>
      </div>
    </div>
    <!-- Striped rows start -->
    <section id="multiple-column-form">
      <div class="row match-height">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h4 class="card-title">Editar Congregação</h4>
            </div>
            <div class="card-content">
              <div class="card-body">
                <div class="row">
                  <div class="col-md-6 col-12">
                    <%= simple_form_for @congregacao, url: congregacao_path(@congregacao), html: { class: 'form' }, method: :patch do |f| %>
                      <%= f.error_notification %>
                      <div class="form-group">
                        <%= f.input :descricao, label: 'Nome da Congregação', input_html: { class: 'form-control' } %>
                      </div>
                      <div class="form-group">
                        <%= f.button :submit, 'Atualizar', class: 'btn btn-primary' %>
                        <%= link_to 'Voltar', congregacoes_path, class: 'btn btn-secondary' %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/congregacoes/index.html.erb
<div id="main">
  <header class="mb-3">
    <a href="#" class="burger-btn d-block d-xl-none">
      <i class="bi bi-justify fs-3"></i>
    </a>
  </header>
  <div class="page-heading">
    <div class="page-title">
      <div class="row">
        <div class="col-12 col-md-6 order-md-1 order-last">
          <h3>Congregação</h3>
          <p class="text-subtitle text-muted"></p>
        </div>
        <div class="col-12 col-md-6 order-md-2 order-first">
        </div>
      </div>
    </div>
    <!-- Striped rows start -->
    <section class="section">
      <div class="row" id="table-striped">
        <div class="col-12">
          <div class="card">
            <div class="card-content">
              <div class="card-body">
                <!-- table striped -->
                <div class="table-responsive">
                  <table class="table table-striped mb-0">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Descrição</th>
                        <th>Ações</th>
                      </tr>
                    </thead>
                    <tbody>
                      <%@congregacoes.each do |congregacao|%>
                        <tr>
                          <td> <%= congregacao.id %> </td>
                          <td> <%= congregacao.descricao%> </td>
                          <td>
                            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split"
        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="bi bi-gear dropdown-icon"></i>
                            </button>
                            <div class="dropdown-menu">
                              <%= link_to congregacao_path(congregacao), class: "dropdown-item" do %>
                                <i class="bi bi-eye"></i> Visualizar
                              <% end %>
                              <%= link_to edit_congregacao_path(congregacao), class: "dropdown-item" do %>
                                <i class="bi bi-pencil"></i> Editar
                              <% end %>
                              <%= button_to congregacao_path(congregacao), method: :delete, class: "dropdown-item" do %>
                                <i class="bi bi-trash"></i> Deletar
                              <% end %>
                            </div>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/congregacoes/new.html.erb
<div id="main">
  <header class="mb-3">
    <a href="#" class="burger-btn d-block d-xl-none">
      <i class="bi bi-justify fs-3"></i>
    </a>
  </header>
  <div class="page-heading">
    <div class="page-title">
      <div class="row">
        <div class="col-12 col-md-6 order-md-1 order-last">
          <h3>Congregação</h3>
          <p class="text-subtitle text-muted"></p>
        </div>
        <div class="col-12 col-md-6 order-md-2 order-first">
        </div>
      </div>
    </div>
    <!-- Striped rows start -->
    <section id="multiple-column-form">
      <div class="row match-height">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h4 class="card-title">Nova Congregação</h4>
            </div>
            <div class="card-content">
              <div class="card-body">
                <div class="row">
                  <div class="col-md-6 col-12">
                    <%= simple_form_for @congregacao, html: { class: 'form' } do |f| %>
                      <%= f.error_notification %>
                      <div class="form-group">
                        <%= f.input :descricao, label: 'Nome da Congregação', input_html: { class: 'form-control' } %>
                      </div>
                      <div class="form-group">
                        <%= f.button :submit, 'Salvar', class: 'btn btn-primary' %>
                        <%= link_to 'Voltar', congregacoes_path, class: 'btn btn-secondary' %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

app/views/congregacoes/show.html.erb
<!--<div id="main">
  <header class="mb-3">
    <a href="#" class="burger-btn d-block d-xl-none">
      <i class="bi bi-justify fs-3"></i>
    </a>
  </header>
  <div class="page-heading">
    <div class="page-title">
      <div class="row">
        <div class="col-12 col-md-6 order-md-1 order-last">
          <h3><%= @congregacao.descricao%></h3>
          <p class="text-subtitle text-muted"></p>
        </div>
        <div class="col-12 col-md-6 order-md-2 order-first">
        </div>
      </div>
    </div>
   Striped rows start 
<section class="section">
  <div class="row" id="table-striped">
    <div class="col-12">
      <div class="card">
        <div class="card-content">
          <div class="card-body">
            
          </div> 
        </div> 
      </div> 
    </div> 
  </div> 
</section>-->!

app/views/entradas/edit.html.erb
<div id="main">
  <header class="mb-3">
    <a href="#" class="burger-btn d-block d-xl-none">
      <i class="bi bi-justify fs-3"></i>
    </a>
  </header>
  <div class="page-heading">
    <div class="page-title">
      <div class="row">
        <div class="col-12 col-md-6 order-md-1 order-last">
          <h3>Congregação</h3>
          <p class="text-subtitle text-muted"></p>
        </div>
        <div class="col-12 col-md-6 order-md-2 order-first">
        </div>
      </div>
    </div>
    <!-- Striped rows start -->
    <section id="multiple-column-form">
      <div class="row match-height">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h4 class="card-title">Nova Entrada</h4>
            </div>
            <div class="card-content">
              <div class="card-body">
                <div class="row">
                  <div class="col-md-6 col-12">
                    <%= simple_form_for @entrada, html: { class: 'form' } do |f| %>
                      <%= f.error_notification %>
                      <!-- Campo de seleção para Congregação -->
                      <div class="form-group">
                        <%= f.input :congregacao_id, 
          as: :select, 
          collection: @congregacoes.map { |c| [c.descricao, c.id] }, 
          label: 'Congregação', 
          input_html: { class: 'form-control' } %>
                      </div>
                      <!-- Campo para valor -->
                      <div class="form-group">
                        <%= f.input :valor, 
          as: :numeric, 
          label: 'Valor', 
          input_html: { class: 'form-control' } %>
                      </div>
                      <!-- Botão de submissão -->
                      <div class="form-group">
                        <%= f.button :submit, 'Salvar', class: 'btn btn-primary' %>
                        <%= link_to 'Voltar', congregacoes_path, class: 'btn btn-secondary' %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

app/views/entradas/index.html.erb
<div id="main">
  <header class="mb-3">
    <a href="#" class="burger-btn d-block d-xl-none">
      <i class="bi bi-justify fs-3"></i>
    </a>
  </header>
  <div class="page-heading">
    <div class="page-title">
      <div class="row">
        <div class="col-12 col-md-6 order-md-1 order-last">
          <h3>Congregação</h3>
          <p class="text-subtitle text-muted"></p>
        </div>
        <div class="col-12 col-md-6 order-md-2 order-first">
        </div>
      </div>
    </div>
    <!-- Striped rows start -->
    <section class="section">
      <div class="row" id="table-striped">
        <div class="col-12">
          <div class="card">
            <div class="card-content">
              <div class="card-body">
                <!-- table striped -->
                <div class="table-responsive">
                  <table class="table table-striped mb-0">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Valor</th>
                        <th>Ações</th>
                      </tr>
                    </thead>
                    <tbody>
                      <%@entradas.each_with_index do |entrada, index|%>
                        <tr>
                          <td> <%= index + 1 %> </td>
                          <td> <%= entrada.congregacao.descricao %> </td>
                          <td> <%= entrada.trimestre%> </td>
                          <td> <%= entrada.ano%> </td>
                          <td> <%= entrada.valor%> </td>
                          <td>
                            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split"
        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="bi bi-gear dropdown-icon"></i>
                            </button>
                            <div class="dropdown-menu">
                              <%= link_to entrada_path(entrada), class: "dropdown-item" do %>
                                <i class="bi bi-eye"></i> Visualizar
                              <% end %>
                              <%= link_to edit_entrada_path(entrada), class: "dropdown-item" do %>
                                <i class="bi bi-pencil"></i> Editar
                              <% end %>
                              <%= button_to entrada_path(entrada), method: :delete, class: "dropdown-item" do %>
                                <i class="bi bi-trash"></i> Deletar
                              <% end %>
                            </div>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/entradas/new.html.erb
<div id="main">
  <header class="mb-3">
    <a href="#" class="burger-btn d-block d-xl-none">
      <i class="bi bi-justify fs-3"></i>
    </a>
  </header>
  <div class="page-heading">
    <div class="page-title">
      <div class="row">
        <div class="col-12 col-md-6 order-md-1 order-last">
          <h3>Congregação</h3>
          <p class="text-subtitle text-muted"></p>
        </div>
        <div class="col-12 col-md-6 order-md-2 order-first">
        </div>
      </div>
    </div>
    <!-- Striped rows start -->
    <section id="multiple-column-form">
      <div class="row match-height">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h4 class="card-title">Nova Entrada</h4>
            </div>
            <div class="card-content">
              <div class="card-body">
                <div class="row">
                  <div class="col-md-6 col-12">
                    <%= simple_form_for @entrada, html: { class: 'form' } do |f| %>
                      <%= f.error_notification %>
                      <!-- Campo de seleção para Congregação -->
                      <div class="form-group">
                        <%= f.input :congregacao_id, 
                          as: :select, 
                          collection: @congregacoes.map { |c| [c.descricao, c.id] }, 
                          label: 'Congregação', 
                          input_html: { class: 'form-control' } %>
                      </div>
                      
                      <div class="form-group">
                        <%= f.input :trimestre, 
                        as: :select, 
                        collection: (1..4).map { |n| [n, n] }, 
                        label: 'Trimestre', 
                        input_html: { class: 'form-control' } %>
                      </div>

                      <div class="form-group">
                        <%= f.input :ano, 
                        as: :select, 
                        collection: (2020..2028).map { |year| [year, year] }, 
                        label: 'Ano', 
                        input_html: { class: 'form-control' } %>
                      </div>
                      <!-- Campo para valor -->
                      <div class="form-group">
                        <%= f.input :valor, 
                        as: :numeric, 
                        label: 'Valor', 
                        input_html: { class: 'form-control' } %>
                      </div>
                      <!-- Botão de submissão -->
                      <div class="form-group">
                        <%= f.button :submit, 'Salvar', class: 'btn btn-primary' %>
                        <%= link_to 'Voltar', congregacoes_path, class: 'btn btn-secondary' %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slg</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <!-- CSS Files -->
    <link rel="stylesheet" href="/mazer-1.0.0/dist/assets/css/bootstrap.css">
    <link rel="stylesheet" href="/mazer-1.0.0/dist/assets/vendors/iconly/bold.css">
    <link rel="stylesheet" href="/mazer-1.0.0/dist/assets/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="/mazer-1.0.0/dist/assets/vendors/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="/mazer-1.0.0/dist/assets/css/app.css">
    <link rel="shortcut icon" href="/mazer-1.0.0/dist/assets/images/favicon.svg" type="image/x-icon">
  </head>
  <body>
    <%= render 'shared/sidebar' %>
    <%= yield %>
    <!-- JS Files -->
    <script src="/mazer-1.0.0/dist/assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="/mazer-1.0.0/dist/assets/js/bootstrap.bundle.min.js"></script>
    <script src="/mazer-1.0.0/dist/assets/vendors/apexcharts/apexcharts.js"></script>
    <script src="/mazer-1.0.0/dist/assets/js/pages/dashboard.js"></script>
    <script src="/mazer-1.0.0/dist/assets/js/main.js"></script>
  </body>
</html>

app/views/literaturas/edit.html.erb
<div id="main">
  <header class="mb-3">
    <a href="#" class="burger-btn d-block d-xl-none">
      <i class="bi bi-justify fs-3"></i>
    </a>
  </header>
  <div class="page-heading">
    <div class="page-title">
      <div class="row">
        <div class="col-12 col-md-6 order-md-1 order-last">
          <h3>Congregação</h3>
          <p class="text-subtitle text-muted"></p>
        </div>
        <div class="col-12 col-md-6 order-md-2 order-first">
        </div>
      </div>
    </div>
    <!-- Striped rows start -->
    <section id="multiple-column-form">
      <div class="row match-height">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h4 class="card-title">Nova Literatura</h4>
            </div>
            <div class="card-content">
              <div class="card-body">
                <div class="row">
                  <div class="col-md-6 col-12">
                    <%= simple_form_for @literatura, html: { class: 'form' } do |f| %>
                      <%= f.error_notification %>
                      <!-- Campo de seleção para Congregação -->
                      <div class="form-group">
                        <%= f.input :congregacao_id, 
                        as: :select, 
                        collection: @congregacoes.map { |c| [c.descricao, c.id] }, 
                        label: 'Congregação', 
                        input_html: { class: 'form-control' } %>
                      </div>

                      <div class="form-group">
                                            <%= f.input :trimestre, 
                        as: :select, 
                        collection: (1..4).map { |n| [n, n] }, 
                        label: 'Trimestre', 
                        input_html: { class: 'form-control' } %>
                      </div>

                      <div class="form-group">
                                            <%= f.input :ano, 
                        as: :select, 
                        collection: (2020..2028).map { |year| [year, year] }, 
                        label: 'Ano', 
                        input_html: { class: 'form-control' } %>
                      </div>
                      <!-- Campo para valor -->
                      <div class="form-group">
                                      <%= f.input :valor, 
                        as: :numeric, 
                        label: 'Valor', 
                        input_html: { class: 'form-control' } %>
                      </div>
                      <!-- Botão de submissão -->
                      <div class="form-group">
                        <%= f.button :submit, 'Salvar', class: 'btn btn-primary' %>
                        <%= link_to 'Voltar', congregacoes_path, class: 'btn btn-secondary' %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

app/views/literaturas/index.html.erb
<div id="main">
  <header class="mb-3">
    <a href="#" class="burger-btn d-block d-xl-none">
      <i class="bi bi-justify fs-3"></i>
    </a>
  </header>
  <div class="page-heading">
    <div class="page-title">
      <div class="row">
        <div class="col-12 col-md-6 order-md-1 order-last">
          <h3>Congregação</h3>
          <p class="text-subtitle text-muted"></p>
        </div>
        <div class="col-12 col-md-6 order-md-2 order-first">
        </div>
      </div>
    </div>
    <!-- Striped rows start -->
    <section class="section">
      <div class="row" id="table-striped">
        <div class="col-12">
          <div class="card">
            <div class="card-content">
              <div class="card-body">
                <!-- table striped -->
                <div class="table-responsive">
                  <table class="table table-striped mb-0">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Congregação</th>
                        <th>Trimestre</th>
                        <th>Ano</th>
                        <th>Valor</th>
                      </tr>
                    </thead>
                    <tbody>
                      <%@literaturas.each do |literatura|%>
                        <tr>
                          <td> <%= literatura.congregacao.descricao %> </td>
                          <td> <%= literatura.valor%> </td>
                          <td> <%= literatura.trimestre%> </td>
                          <td> <%= literatura.ano%> </td>
                          <td>
                            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split"
        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="bi bi-gear dropdown-icon"></i>
                            </button>
                            <div class="dropdown-menu">
                              <%= link_to literatura_path(literatura), class: "dropdown-item" do %>
                                <i class="bi bi-eye"></i> Visualizar
                              <% end %>
                              <%= link_to edit_literatura_path(literatura), class: "dropdown-item" do %>
                                <i class="bi bi-pencil"></i> Editar
                              <% end %>
                              <%= button_to literatura_path(literatura), method: :delete, class: "dropdown-item" do %>
                                <i class="bi bi-trash"></i> Deletar
                              <% end %>
                            </div>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div id="sidebar" class="active">
  <div class="sidebar-wrapper active">
    <div class="sidebar-header">
      <div class="d-flex justify-content-between">
        <div class="logo">
        </div>
        <div class="toggler">
          <a href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
        </div>
      </div>
    </div>
    <div class="sidebar-menu">
      <ul class="menu">
        <li class="sidebar-title">Menu</li>
        <li class="sidebar-item active ">
          <%= link_to congregacoes_path, class:'sidebar-link' do %>
            <i class="bi bi-house-door"></i>
            <span>Congregações</span>    
          <% end %>
        </li>
        <li class="sidebar-item  has-sub">
          <a href="#" class='sidebar-link'>
            <i class="bi bi-file-earmark-spreadsheet"></i>
            <span>Literatura</span>
          </a>
          <ul class="submenu ">
            <li class="submenu-item ">
              <%= link_to literaturas_path, class: 'sidebar-link' do%>
                Valores
              <%end%>
            </li>
            <li class="submenu-item ">
              <%= link_to literaturas_relatorio_path, class: 'sidebar-link' do%>
                Relatório
              <%end%>
            </li>
          </ul>
        </li>
        <li class="sidebar-item  ">
          <%= link_to entradas_path, class:'sidebar-link' do %>
            <i class="fa-solid fa-money-bill"></i>           <span>Entradas</span>
          <% end %>
        </li>
      </ul>
    </div>
    <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
  </div>
</div>